swagger: "2.0"
info:
  description: "Interactive AuthNexus API documentation"
  version: "1.0.0"
  title: "AuthNexus Doc"
host: "localhost:3000"
basePath: "/"
tags:
  - name: "Users"
    description: "Users and Auths APIs"
  - name: "Documents"
    description: "AWS SDK File Upload"
  - name: "Profile"
    description: "Update User Profile"
  - name: "Payment"
    description: "RazorPay integration"
schemes:
  - "http"
  - "https"
paths:
  /users:
    post:
      tags:
        - "Users"
      summary: "Register new user"
      description: ""
      operationId: "registerUsers"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User object for registration"
          required: true
          schema:
            $ref: "#/definitions/Users"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "User registration completed successfully"
      security:
        - api_key: []
    get: 
      tags:
        - "Users"
      summary: "Retrieve all users"
      description: ""
      operationId: "getUsers"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Users"
        "400":
          description: "Invalid request"
  /users/login:
    post:
      tags:
        - "Users"
      summary: "Login existing user"
      description: ""
      operationId: "loginUser"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Login information"
          required: true
          schema:
            $ref: "#/definitions/LoginUser"
      responses:
        "201":
          description: "Login successfully."
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        "400":
          description: "Invalid params supplied"
  /users/send-otp:
    post:
      tags:
        - "Users"
      summary: "Send OTP for MFA"
      description: ""
      operationId: "sendOtp"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Email for MFA"
          required: true
          schema:
            $ref: "#/definitions/SendOtp"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "OTP sent successfully!"
      security:
        - api_key: []
  /users/verify-otp:
    post:
      tags:
        - "Users"
      summary: "Verify OTP for MFA"
      description: ""
      operationId: "verifyOtp"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Email and OTP for MFA"
          required: true
          schema:
            $ref: "#/definitions/VerifyOtp"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "MFA completed successfully!"
      security:
        - api_key: []
  /users/forgot-password:
    post:
      tags:
        - "Users"
      summary: "Forgot password"
      description: ""
      operationId: "forgotPassword"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Forgot password"
          required: true
          schema:
            $ref: "#/definitions/ForgotPassword"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Password reset instructions sent successfully!"
      security:
        - api_key: []
  /users/reset-password:
    post:
      tags:
        - "Users"
      summary: "Reset password"
      description: ""
      operationId: "resetPassword"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Reset password"
          required: true
          schema:
            $ref: "#/definitions/ResetPassword"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Password updated successfully!"
      security:
        - api_key: []
  /document:
    post:
      tags:
        - "Documents"
      summary: "Upload document"
      description: "AWS SDK File upload APIs"
      operationId: "uploadDocument"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - in: "formData"
          name: "file"
          type: "file"
          description: "File to upload"
          required: true
      responses:
        "200":
          description: "Successful operation"
  /document/{filekey}:
    get:
      tags:
        - "Documents"
      summary: "Download a document"
      description: "Download a file"
      operationId: "getDocumentByFileKey"
      produces:
        - "application/octet-stream"
      parameters:
        - name: "filekey"
          in: "path"
          description: "File Key"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "file"
        "404":
          description: "File not found"
  /profile:
    post:
      tags:
        - "Profile"
      summary: "Create or update user profile"
      description: ""
      operationId: "createOrUpdateUserProfile"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User profile"
          required: true
          schema:
            $ref: "#/definitions/Profile"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "User profile created/updated successfully"
    get:
      tags:
        - "Profile"
      summary: "Retrieve all user profiles"
      description: ""
      operationId: "getAllUserProfiles"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Profile"
        "400":
          description: "Invalid input"
  /profile/{userId}:
    put:
      tags:
        - "Profile"
      summary: "Update user profile"
      description: ""
      operationId: "updateUserProfile"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of user to update"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Updated user profile"
          required: true
          schema:
            $ref: "#/definitions/Profile"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "User profile updated successfully"
    get:
      tags:
        - "Profile"
      summary: "Get user profile by userId"
      description: ""
      operationId: "getUserProfileByUserId"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of user to retrieve"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Profile"
        "400":
          description: "Invalid userId supplied"
        "404":
          description: "User not found"
  /payment/order:
    post:
      tags:
        - "Payment"
      summary: "Create Razorpay Pay Order"
      description: ""
      operationId: "createRazorPayOrder"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Razorpay Payment"
          required: true
          schema:
            $ref: "#/definitions/OrderPayment"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Order created successfully"
  /payment/verify-payment:
    post:
      tags:
        - "Payment"
      summary: "Razorpay Payment Verification"
      description: ""
      operationId: "verifyRazorPayPayment"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Razorpay Payment Verification"
          required: true
          schema:
            $ref: "#/definitions/VerifyPayment"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Payment verified successfully"
  /payment/refund:
    post:
      tags:
        - "Payment"
      summary: "Razorpay Refund"
      description: ""
      operationId: "refundRazorPayPayment"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Razorpay Refund"
          required: true
          schema:
            $ref: "#/definitions/RefundPayment"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Successfully refunded"
  /payment/partial-refund:
    post:
      tags:
        - "Payment"
      summary: "Razorpay Partial Refund"
      description: ""
      operationId: "partialRefundRazorPayPayment"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Partial Refund Razorpay Payment"
          required: true
          schema:
            $ref: "#/definitions/PartialRefund"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Successfully refunded"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Users:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      role:
        type: "string"
    xml:
      name: "Users"
  LoginUser:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
      role:
        type: "string"
    xml:
      name: "LoginUser"
  ForgotPassword:
    type: "object"
    properties:
      email:
        type: "string"
    xml:
      name: "ForgotPassword"
  PasswordResets:
    type: "object"
    properties:
      email:
        type: "string"
      newPassword:
        type: "string"
    xml:
      name: "PasswordResets"
  SendOtp:
    type: "object"
    properties:
      email:
        type: "string"
    xml:
      name: "SendOtp"
  VerifyOtp:
    type: "object"
    properties:
      email: 
        type: "string"
      otp:
        type: "string"
    xml:
      name: "VerifyOtp"
  ResetPassword:
    type: "object"
    properties:
      email: 
        type: "string"
      newPassword:
        type: "string"
    xml:
      name: "ResetPassword"
  Profile:
    type: "object"
    properties:
      userId: 
        type: "string"
      firstname: 
        type: "string"
      lastname:
        type: "string"
      DOB:
        type: "string"
      mobileNumber: 
        type: "string"
      email:
        type: "string"
    xml:
      name: "Profile"
  OrderPayment:
    type: "object"
    properties:
      orderId:
        type: "string"
      amount: 
        type: "number"
      currency: 
        type: "string"
      userId: 
        type: "string"
      customerName:
        type: "string"
      customerEmail:
        type: "string"
      customerPhone:
        type: "string"
    xml:
      name: "OrderPayment"
  VerifyPayment:
    type: "object"
    properties:
      razorpay_payment_id:
        type: "string"
      razorpay_order_id: 
        type: "string"
      razorpay_signature: 
        type: "string"
    xml:
      name: "VerifyPayment"
  RefundPayment:
    type: "object"
    properties:
      paymentId:
        type: "string"
    xml:
      name: "RefundPayment"
  PartialRefund:
    type: "object"
    properties: 
      paymentId: 
        type: "string"
      amount:
        type: "number"
    xml:
      name: "PartialRefund"
